steps:
  01-datagen-and-routing:
    image: registry.ubitech.eu/cs3/rnd/h2020-datacloud/datacloud-scenarios/tellucare-edge:latest
    replicas: 1
    network:
        ingress-bandwidth: 1M
        egress-bandwidth: 1M
    resource-provider:
        edge
    environment:
      MQTT_HOST: oslo.sct.sintef.no
      MQTT_USERNAME: TGW000000000
      MQTT_CLIENT_ID: "TGWDATACLOUD"
      MQTT_PASS: "?????"
      MQTT_PORT: '1883'
  02-storage-and-analytics:
    image: registry.ubitech.eu/cs3/rnd/h2020-datacloud/datacloud-scenarios/tellucare-api:latest
    depends_on:
      - 01-datagen-and-routing
    resources:
        limits:
          cpus: '1'
          memory: 1024M
          storage: 8192M
    replicas: 10
    network:
        ingress-bandwidth: 1M
        egress-bandwidth: 1M
    resource-provider:
        cloud
    environment:
      RABBITMQ_HOST: oslo.sct.sintef.no:5672
      RABBITMQ_USERNAME: tellucareapi
      RABBITMQ_PASSWORD: "?????"
      FHIR_URL: https://tellucloud-fhir.sintef.cloud
  03-application-logic:
    image: registry.ubitech.eu/cs3/rnd/h2020-datacloud/datacloud-scenarios/tellucare-application-logic:latest
    depends_on:
      - 02-storage-and-analytics
    resources:
        limits:
          cpus: '0.5'
          memory: 512M
          storage: 1024M
    replicas: 5
    network:
        ingress-bandwidth: 0.5M
        egress-bandwidth: 0.5M
    resource-provider:
        cloud
    environment:
      FHIR_URL: https://tellucloud-fhir.sintef.cloud/
      RABBITMQ_HOST: oslo.sct.sintef.no:5672
      RABBITMQ_USERNAME: tellucareapplicationlogic
      RABBITMQ_PASSWORD: "?????"