FROM alpine:latest
RUN apk --update add python3 py3-numpy && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip 
RUN pip3 install --no-cache-dir  PyYAML matching

COPY . .

CMD ["python3", "./ada-match-time-optimized.py"]