apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-accuracy-training
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-accuracy-training
  template:
    metadata:
      labels:
        app: high-accuracy-training
    spec:
      containers:
      - name: hightrain
        image: sina88/hightrain:hpa
        imagePullPolicy: IfNotPresent
        resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
          requests:
            cpu: "3"
            memory: "2Gi"
