apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kubemq
  name: kubemq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kubemq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kubemq
    spec:
      containers:
      - env:
        - name: KUBEMQ_HOST
          value: kubemq
        - name: KUBEMQ_TOKEN
          value: '"8297ae1b-d2bc-40b4-bf95-39a67162984d"'
        image: kubemq/kubemq:latest
        imagePullPolicy: ""
        name: kubemq
        ports:
        - containerPort: 8080
        - containerPort: 9090
        - containerPort: 50000
        resources: {}
        volumeMounts:
        - mountPath: /store
          name: kubemq-vol
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /home/yared/Development/Repositories/ew-shopp-evaluation
        name: kubemq-vol
status: {}
