apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kubemq
  name: kubemq
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9090"
    port: 9090
    targetPort: 9090
  - name: "50000"
    port: 50000
    targetPort: 50000
  selector:
    io.kompose.service: kubemq
status:
  loadBalancer: {}
